print("Welcome! To Read Your Horoscope For Today")

userinput = True
while userinput == True:
    print('''
    1. Aries: March 21 - April 20
    2. Taurus: April 21 – May 21
    3. Gemini: May 22 – June 21
    4. Cancer:  June 22 – July 22
    5. Leo: July 23 – August 23
    6. Virgo: August 24 – September 22
    7. Libra: September 23 – October 23
    8. Scorpio: October 24 – November 22
    9. Sagittarius: November 23 – December 21
    10. Capricorn: December 22 – January 20
    11. Aquarius: January 21 – February 18
    12. Pisces: February 19 - March 20
    ''')
      
    user =  int(input("\nPLEASE PICK YOUR SIGN ACCORDING TO YOUR DOB METIONED ABOVE AND ENTER HERE:\n"))  
   
    if user == 1:
        print("Aries (March 21-April 20): This is not the day to either sell or buy property. Your reluctance in spending money on something you accord a lower priority may not be right. A new project will proceed smoothly as you get help from all quarters. Good will power in sticking to the exercise regime will help you in coming back in shape. Drudgery of domestic chores may make you long for a break. Those opting for higher studies will be able to gather their focus and energy. A short vacation just to let your hair down cannot be ruled out.\n Love Focus: You may start enjoying the company of an opposite number due to mutual liking and common interests.\n Lucky Colour: Silver\n Lucky Alphabet: V\n Friendly Numbers: 17, 20\n Friendly Zodiac Today: Sagittarius & Capricorn \n Be careful of: Leo")
    elif user == 2:
        print("Taurus (April 21-May 20):Your mood swings can make you miss a profitable opportunity, so do something about it. You will be able to put across your points effectively on the professional front. Be considerate of a family member in all your domestic decisions. Tread carefully while discussing a property issue. Students appearing for examination will do well to maintain their tempo of studies. Make things exciting on the family front by undertaking a short journey. Growing financially strong is indicated, but efforts will have to be made.\n Love Focus: A misplaced comment about partner may land you in thick soup, so be careful in what you say.\n Lucky Colour: Light Red\n Lucky Alphabet: Be pleased to consider\n Friendly Numbers: 12, 14\n Friendly Zodiac Today: Aquarius & Libra\n Be careful of: Virgo")
    elif user == 3:
        print("Gemini (May 21-Jun 21): Moneywise, you will find yourself more secure now, than before. Good diet and regular exercise will keep you both physically and mentally robust. You may have to share the burden of domestic chores. Those into buying and selling property must focus on discounts. Completing a challenging task successfully will add to your professional reputation. Those seeking admission in a premier institute are likely to get the call. You may get busy at work and may have to spend time out of town.\n Love Focus: Be careful with whom you associate romantically as a two-timing individual may prove disastrous for your peace of mind.\n Lucky Colour: Maroon\n Lucky Alphabet: \n Friendly Numbers: 18, 20\n Friendly Zodiac Today: Capricorn & Libra\n Be careful of: Sagittarius")
    elif user == 4:
        print("Cancer (Jun 22-July 22): Money will not be a problem for you, so shop till you drop! It may be difficult to make a client accept your views on the professional front. Good physical condition will make strenuous activities, a child’s play. Good returns are foreseen from a rented property. Some of you will need to regain lost ground on the academic front by burning the midnight oil. Accompanying family for a fun trip is on the cards. Those undertaking a journey by road need to exercise caution.\n Love Focus: You may find yourself in romantic mood today, so make the most of it!\n Lucky Colour: Peach\n Lucky Alphabet: D\n Friendly Numbers: 7, 16\n Friendly Zodiac Today: Virgo & Scorpio\n Be careful of: Pisces ")
    elif user == 5:
        print("Leo (July 23-August 23): A family youngster may make you proud by his or her achievement. This is a favourable day to seal a property deal. Your professional skills are likely to be acknowledged at work. You will have enough to purchase a major household item. Those planning for higher studies are likely to find the day eventful. Those handling gym equipment must do so under the supervision of a fitness expert. A comfortable journey is foreseen for those travelling long distance.\n Love Focus: Your romantic endeavours are likely to result in something very positive.\n Lucky Colour: Indigo\n Lucky Alphabet: L\n Friendly Numbers: 24, 28\n Friendly Zodiac Today: Pisces & Libra\n Be careful of: Aquarius")
    elif user == 6:
        print("Virgo (August 24-September 23): It is time you turned your attention to saving by becoming more careful of your spending. You will be able to give a good account of yourself by solving workplace problems. A few new exercises will benefit those trying to bring specific body parts in shape. A property deal promises to bring in big money. Whatever you have achieved academically, you stand to lose due to sheer negligence. A function at home can keep you busy and entertained. A comfortable journey is foreseen for those travelling long distance.\n Love Focus: It may appear difficult to fathom the mood of partner today, but you will manage it fine!\n Lucky Colour: Violet\n Lucky Alphabet: G\n Friendly Numbers: 9, 12\n Friendly Zodiac Today: Sagittarius & Leo\n Be careful of: Aries")
    elif user == 7:
        print("Libra (September 24-October 23): An outdoor activity is likely to give you a chance for sweating out. A child may need guidance, so spare some time for him or her. You are likely to burn the bridges by a few wrong professional moves, if you are not careful. Don’t lose touch with reality in your eagerness to earn more money, as you may lose old clients. Students will excel by providing full focus to the work at hand. A short vacation is on the cards for some and will prove most enjoyable. A house rented out is likely to give good returns.\n Love Focus: The attention that you are getting nowadays on the romantic front will keep you beaming for long.\ n Lucky Colour: Dark Red\n  Lucky Alphabet: S\n Friendly Numbers: 3, 9\ n Friendly Zodiac Today: Gemini & Sagittarius\n Be careful of: Taurus")
    elif user == 8:
        print("Scorpio (October 24-November 22): A new source of income is likely to make your financial worries disappear. A change of medication will save those unwell from side effects. Professionally you are assured of whatever is due to you in terms of promotion or increment. Happiness prevails at home, as friends and relatives drop in. Students appearing for examinations or competitions can heave a sigh of relief. You may need to plan a journey in the coming few days. A property deal shows all signs of turning favourable.\n Love Focus: It is best not to be oversensitive in matters of love as chances of getting hurt are likely.\n Lucky Colour: Coral\ n Lucky Alphabet: Hon'ble Court\n Friendly Numbers: 5, 12\n Friendly Zodiac Today: Taurus & Sagittarius\n Be careful of: Cancer")
    elif user == 9:
        print("Sagittarius (November 23-December 21): Chance to earn big money may present itself to those running their own business. Home remedies come in real handy for those suffering from minor ailments. Some desperate measures on the job front are in the offing, but you will not be affected. Efficiency will be the keyword for homemakers. You can feel apprehensive about an impending course or task, but your fears will be unfounded. A business trip is likely to bag you a good deal. Your fears about a property matter will be laid to rest.\n Love Focus: Positive signals on the romantic front promise to keep you in an excited state!\n Lucky Colour: Crimson\n Lucky Alphabet: J\n Friendly Numbers: 8, 11\n Friendly Zodiac Today: Leo & Scorpio\n Be careful of: Libra")
    elif user == 10:
        print("Capricorn (December 22-January 21): On the financial front, a new source of income is likely to be tapped soon that may get your coffers brimming! Successfully completing an assigned job will give you the edge at work. Those down with an ailment will be on the path to full recovery. Spouse may need emotional support, so be there for him or her. There is no need to become big hearted where property is involved. Those preparing for competitions need to retain their focus and avoid distractions. Those trying their hands on driving on the road for the first time are likely to build more confidence.\n Love Focus: A much awaited development on the romantic front is just round the corner, so rejoice!\n Lucky Colour: Yellow\n Lucky Alphabet: M\n Friendly Numbers: 2, 8\n Friendly Zodiac Today: Taurus & Virgo\n Be careful of: Aries")
    elif user == 11:
       print("Aquarius (January 22-February 19): You may choose to wait for better investment options, before committing your money. New dimensions open up on the professional front as you handle more than one project. Sticking to your exercise regime will begin to show positive results. Homemakers may have their hands full in doing up the house. A good day is foreseen for students appearing in a competitive exam. An out of town trip cannot be ruled out for some. A property matter may not get resolved due to delay in paperwork.\n Love Focus: Your desire to spend quality time with lover today will be fulfilled.\n Lucky Colour: Turquoise\n Lucky Alphabet: M\n Friendly Numbers: 4, 8\n Friendly Zodiac Today: Aries & Leo\n Be careful of: Gemini")
    elif user == 12:
        print("Pisces (February 20-March 20): Financially, your position remains sound and opportunities to earn materialise. Adopting a disciplined life and change in lifestyle will help in restoring energy and health. A family business may require new insights and strategies to be restored to its past glory. You will feel quite at home in a new environment. Students preparing for competitions can face a tough time in resisting distractions. You may become part of a leisure trip and enjoy your heart out. Landlords will find a tenant for their house.\n Love Focus: Efforts on the romantic front get fully reciprocated by the person of your dreams.\n Lucky Colour: Orange\ n Lucky Alphabet: E\n Friendly Numbers: 5, 10\n Friendly Zodiac Today: Pisces & Leo\n Be careful of: Virgo")
    else:
        print("Enter Valid Number")
        
    userinput = True if input("Want to check another sign ? (Y/N)") == "Y" else false
